services:
  next-app:
    container_name: next-frontend
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:80"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_SERVER_URL_AWS=${NEXT_PUBLIC_SERVER_URL_AWS}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge