services:
  next-app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:80"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=80
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next